---
title: "When You Install Softwares"
---

<style type="text/css">

body, td {
   font-size: 15px;
}
pre {
  font-size: 15px
}
</style>


Because I was an window OS user for more than 20 years, one of the strangest things as a beginner was about how to install programs. When you try to install in Linux,

- you can directly install in *terminal*,
- you are gonna be given files of the form *.deb* in the web,
- you are gonna be given files of the form *.tar.gz* in the web. 

<br>

When using terminal, many softwares are gonna be installed with a package *apt-get*, such as 

$\texttt{sudo apt-get install texlive-latex-base}$

<br>

When you get *.deb* files, you may use *gdebi* packages to install, such as

$\texttt{sudo gdebi rstudio.deb}$

<br>

When you get *.tar.gz* files (ex. named by *rstudio.tar.gz*), you may type in terminal as below:

<br>

$\texttt{tar -xvzf rstudio.tar.gz}$

$\texttt{cd rstudio}$

$\texttt{./configure}$

$\texttt{make}$

$\texttt{sudo make install}$

<br>
<br>    

[back](../linux.html)