---
layout: html_document
---

## 1.1 Fields and $\sigma$-fields

### Fields of Sets

##### Definition(Field)

A class $\mathcal{F}$ of subsets of $\Omega$ is a \tilt{field} over $\Omega$ if

1. $\Omega \in \mathcal{F}.$
2. $\mathcal{F}$ is closed under complementation: $A \in \mathcal{F}$ implies $A^c\in \mathcal{F}$. 
3. $\mathcal{F}$ is closed under finite unions: $A,B \in \mathcal{F}$ implies $A \cup B\in \mathcal{F}$. 

&nbsp;&nbsp;

##### Remark

Note that 1 could be replaced by 

4. $\phi \in {F}$,  

and 3 replaced by

5. $\mathcal{F}$ is closed under finite intersections: $A,B \in \mathcal{F}$ implies $A \cap B\in \mathcal{F}$. 

&nbsp;&nbsp;

##### Definition($\sigma$-Field)

A class $\mathcal{F}$ of subsets of $\Omega$ is a \tilt{$\sigma$-field} if

1. $\Omega \in \mathcal{F}.$
2. $\mathcal{F}$ is closed under complementation: $A \in \mathcal{F}$ implies $A^c\in \mathcal{F}$. 
3. $\mathcal{F}$ is closed under countable unions: $if A_1,A_2, \ldots \in \mathcal{F}$, then $\cup_n A_n \mathcal{F}$. 

&nbsp;&nbsp;

##### Remark
If $\mathcal{F}$ is $\sigma$-field, then it is a field. But, the reverse does not hold.


&nbsp;&nbsp;

##### Lemma 
If $\mathcal{F}$ is a field and $\mathcal{F}$ is closed under countable disjoint unions, then $\mathcal{F}$ is a $\sigma$-field.

(You can construct disjoint sets $B_n, n\ge 1$ which is increasing sequence of sets, $\cup_n A_n = \uplus_n B_n$. Because $\mathcal{F}$ is closed under countable disjoint union, $\cup_n A_n = \uplus_n B_n \in \mathcal{F}$.)


&nbsp;&nbsp;

##### Proposition
$\sigma(\mathcal{C})$ is the smallest $\sigma$-field containing $\mathcal{C}$.


&nbsp;&nbsp;

##### Proposition

Note that

1. If $\mathcal{F}$ is a $\sigma$-field, then $\sigma(\mathcal{F})= \mathcal{F}$.

2. If $\mathcal{C} \subset \mathcal{D}$, then $\sigma(\mathcal{C})\subset \sigma(\mathcal{D})$.

2. If $\mathcal{C} \subset \mathcal{D} \subset \sigma (\mathcal{C})$, then $\sigma(\mathcal{C})= \sigma(\mathcal{D})$.


&nbsp;&nbsp;

##### Definition(Borel $\sigma$-field on $\mathbb{R}$)
The \texttt{Borel $\sigma$-field} on $\mathbb{R}=(-\infty, \infty)$, denoted by $\mathcal{R}$ is defined to be the smallest $\sigma$-field on $\mathbb{R}$ containing 

1. $\mathcal{I}_0 = \{(a,b]: -\infty<a\le<b<\infty\}$ 
2. $\mathcal{I}_1 =\{(-\infty,b]:-\infty<b<\infty\}$ 
3. $\mathcal{I}_2 =\{(a, \infty):-\infty<a<\infty\}$
4. $\mathcal{I}_3 =\{(-\infty,b):-\infty<b<\infty\}$. 
5. $\mathcal{I}_4 =\{[a,\infty):-\infty<a<\infty\}$. 
6. $\mathcal{I}_5 =\{(a,b)-\infty<a\le<b<\infty\}$. 
7. $\mathcal{T}= \{\mbox{open sets in }\mathbb{R}\}$
8. $\mathcal{S}= \{\mbox{closed sets in }\mathbb{R}\}$

e.g. $\sigma(\mathcal{I}_0)= \mathcal{R}.$

(In Korean: 쉽게 Real line에서의 interval 집합으로 이루어진 class의 smallest $\sigma$-field가 Borel $\sigma$-field 라고 생각하자. $\mathbb{R}$은 실수에서의 Entire set이기 때문에, $\Omega$에 $\mathbb{R}$을 놓고 생각하면 쉽게 이해될 것이다.)


