---
title: 2.4. The Integral
output: html_document
---


<style type="text/css">

body, td {
   font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

&nbsp;&nbsp;


In this section, $(\Omega, \mathcal{F}, \mu)$ is taken to be a measure space. Also, unless otherwise stated, any simple function $f=\sum_{i=1}^m a_i I_{A_i}$ is assumed to be $\mathcal{F}$-measurable and to be represented in such a way that $A_i\in \mathcal{F}$ and $A_i=\phi$ for all $i=1,\ldots,m$, and $\Omega=\uplus_{i=1}^m A_i$. 

&nbsp;&nbsp;

##### Lemma(Monotonicity for nonnegative simple functions)
If $f=\sum_{i=1}^m a_iI_{A_i}$ and $g=\sum_{j=1}^n b_jI_{B_j}$ are measurable, extended-real-valued simple functions satisfying $0\le f(\omega) \le g(\omega)$ for all $\omega\in \Omega$, then
$$
\sum_{i=1}^m a_i\mu(A_i)\le\sum_{j=1}^n b_j\mu(B_j).
$$ 

   * 즉, $\int f\mbox{ } d\mu=\sum_{i=1}^m a_i\mu(A_i)\le\sum_{j=1}^n b_j\mu(B_j)=\int g\mbox{ } d\mu$을 의미한다.

&nbsp;&nbsp;


매우매우 중요

##### Definition(Integral)
Assume in this definition that $f:\Omega\rightarrow\bar{\mathbb{R}}$ is measurable-$\mathcal{F}/\mathcal{R}$.

If $f=\sum_{i=1}^m a_iI_{A_i}$ is a nonnegative, real-valued simple function, then *the integral* of $f$ (with respect to $\mu$) is defined to be
$$
\int f \mbox{ }d\mu=\sum_{i=1}^m a_i\mu(A_i).
$$

For general nonnegative $f$,
$$
\int f\mbox{ } d\mu=\sup\left\{ \int g\mbox{ }d\mu  :0\le g\le f, \mbox{ } g \mbox{ simple, real-valued, and measurable.}        \right\}
$$

Finally, for general $f$, we define
$$
\int f\mbox{ } d\mu=\int f^+\mbox{ } d\mu-\int f^-\mbox{ } d\mu
$$
whenever the difference on the right-hand side is well-defined. In this case, we say that the integral exists, and otherwise that the integral fails to exist. 

If both $\int f^+\mbox{ } d\mu$ and $\int f^-\mbox{ } d\mu$ are finite, so that $\int f\mbox{ } d\mu$ exists and is finite, then we say that $f$ is **integrable** w.r.t $\mu$ $(\int |f|d\mu <\infty)$.

&nbsp;

   * Simple function $f$에 대해서 integral은 finite partition들에 대한 measure들의 sum으로 계산된다. 
   
   * Nonnegative general $f$의 integral은 f보다 작거나 같은 simple function의 integral값들의 supremum값이다.

   * General $f$의 integral은 $f^+\ge 0$와 $f^-\ge 0$값으로 나누고, 각각을 Nonnegative general $f$의 integral로 구하여 계산한다. 이 때 이 integral값이 finite하다면 $f$는 integrable하다. 
   
&nbsp;&nbsp;

##### Theorem(Approximation of the integral Using Simple function)
If $f\ge 0$ is measurable-$\mathcal{F}/\mathcal{R}$ and $f_n, n\ge 1$ is a sequence of real-valued simple functions satisfying $0\le f_n \uparrow f$, then
$$
0\le \int f_n \mbox{ }d\mu \uparrow \int f\mbox{ }d\mu.
$$


   * $f_n$은 nonnegative하고 nondecreasing한 simple function이다. 때문에 $f_n$의 integral값(measure값)도 nondecreasing한다. 
   
   
&nbsp;&nbsp;

##### Definition
A property is said to hold **almost everywhere(a.e.)**, or more specifically $\mu$-almost everywhere ($\mu$-a.e.), if the property holds for all $\omega$ in some set $A\in \mathcal{F}$ with $\mu(A^c)=0$. If $\mu$ is a probability measure, then we say that the property holds **almost surely (a.s.)** or **with probability 1 (w.p.1)**.

   * 어떤 property가 $\mu(A)=1$, $\mu(A^c)=0$인 some set $A\in\mathcal{F}$에서 만족한다면 이 property는 almost everywhere 하게 hold한다고 말할 수 있다. 
   
   * Measure값이 0인 partition of $\Omega$에 대해서는 고려하지 않는 의미로 생각할 수 있다. 
   
&nbsp;&nbsp;

##### Theorem

If $f,g:\Omega\rightarrow \bar{\mathbb{R}}$ are measurable functions satisfying $f=g$ a.e., then $\int f\mbox{ }d\mu$ exists if and only if $\int g\mbox{ }d\mu$ exists, and in this case $\int f\mbox{ }d\mu= \int g\mbox{ }d\mu$. In particular, if $f=0$ a.e., then $\int f\mbox{ }d\mu= 0$.


   * 포인트는 만약 $f=g$ a.e. 이고 $f,g$의 integral들이 exist한다면(not $\infty-\infty$), $\int f\mbox{ }d\mu= \int g\mbox{ }d\mu$한다는 것이다.

   * 증명은 $f=g$ a.e.를 이용한다. $A\in \mathcal{F}$가 $f(\omega)=g(\omega)$ for all $\omega\in A$, where $\mu(A^c)=0$을 만족하는 set이라 하면 $\int f\mbox{ }d\mu= \int  fI_A \mbox{ }d\mu= \int gI_A \mbox{ }d\mu=\int g\mbox{ }d\mu$이다 (Exercise). 


   
&nbsp;&nbsp;

##### Theorem(Monotonicity of the Integral for Nonnegative Functions)
Suppose that $f,g:\Omega\rightarrow\bar{\mathbb{R}}$ are measurable-$\mathcal{F}$. If $0\le f\le g$ a.e., then $\int f\mbox{ }d\mu \le \int g\mbox{ }d\mu$.

   * $0\le f\le g$ a.e.라 하자 ($0\le fI_A \le gI_A$ for $A\in \mathcal{F}$ with $\mu(A^c)=0$). 
   
   * $\int f\mbox{ }d\mu= \int  fI_A \mbox{ }d\mu$이고 $\int gI_A \mbox{ }d\mu=\int g\mbox{ }d\mu$이다.
   
   * 때문에 WLOG, $0\le f(\omega)\le g(\omega)$ for all $\omega\in \Omega$라고 가정하자.
   
   * Simple function $h$에 대해 $\int f \mbox{ }d\mu:=\sup\left\{ \int h\mbox{ }d\mu: 0\le h \le f, \mbox{ }\mbox{ h real valued, simple, measurable}  \right\}$이다. 즉 $\int f\mbox{ }d\mu$는 $\int h\mbox{ }d\mu$ 의 upper bound이다. 하지만 이는 $\int g\mbox{ }d\mu$라는 더 우측의 upper bound에 bounded되어있다(End).

&nbsp;&nbsp;



매우 중요

##### Theorem(Monotone Convergence Theorem)
Suppose that $f$ and $f_n,n\ge 1$ are $\mathcal{F}$-measurable, extended-real-valued functions on $\Omega$. 

If $0\le f_n\uparrow f$ a.e., then
$$
\int f_n \mbox{ }d\mu \uparrow \int f \mbox{ }d\mu. 
$$

   * $\iff \lim_n \int f_n\mbox{ }d\mu=\int\lim_n f_n\mbox{ }d\mu$.


&nbsp;&nbsp;


##### Theorem(Basic properties of the Integral)
Suppose throughout that $f,g:\Omega\rightarrow \bar{\mathbb{R}}$ are measurable-$\mathcal{F}$.

1. (Scalar multiplication and integration commute) If $c\in \mathbb{R}$ and $\int f\mbox{ }d\mu$ exists, then $\int cf \mbox{ }d\mu=c\int f \mbox{ }d\mu$.

&nbsp;

2. (Additivity) If $f+g$ is well-defined(not $\infty-\infty$) and $\int f\mbox{ }d\mu$ and  $\int g\mbox{ }d\mu$ exist, then 
$$
  \int (f+g)\mbox{ }d\mu= \int f\mbox{ }d\mu+ \int g\mbox{ }d\mu, 
$$
   
   as long as the expression on the right-hand side is defined. In particular, if $f$ and $g$ are integrable, then so is $f+g$. 

&nbsp;

3. (Linearity) Suppose that $a,b\in \mathbb{R}$, that $af+bg$ is well-defined, and that $\int f\mbox{ }d\mu$ and  $\int g\mbox{ }d\mu$ exist. Then,
$$
  \int (af+bg)\mbox{ }d\mu= a\int f\mbox{ }d\mu+ b\int g\mbox{ }d\mu, 
$$
 
   as long as the expression on the right-hand side is defined. In particular, this holds whenever $f$ and $g$ are integrable.

&nbsp;

4. If $f\ge 0$ and $\mu(f>0)>0$, then $\int f\mbox{ }d\mu>0$.

   * $\mu(f>0)>0$은 $A:=\{w\in \Omega: f(\omega)>0\}$가 공집합이 아니라는 의미이다.
   
   * $A^c=\{w\in \Omega: f(\omega)=0\}$이므로 $\mu(A^c)=\int_{A^c} f\mbox{ }d\mu=\int fI_{A^c}\mbox{ }d\mu=0$이다. 때문에 $f>0$ a.e.이다. 
   
   * if $f=0$ a.e., then $\int f\mbox{ }d\mu= 0$의 역명제로 if $f>0$ a.e., then $\int f\mbox{ }d\mu>0$을 유추할 수 있다(두가지 경우밖에 없기 때문).

&nbsp;

5. If $\int f\mbox{ }d\mu<\infty$, then $f<\infty$ a.e.

   * Integral 값이 $\infty$보다 작다면, $f <\infty$ a.e. 이다. 
   
&nbsp;

6. (Monotonicity) If $f\le g$ a.e., and both  $\int f\mbox{ }d\mu$ and $\int g\mbox{ }d\mu$ exist, then $\int f\mbox{ }d\mu\le \int g\mbox{ }d\mu$.

   * Integral을 씌워도 부등호는 같다.

&nbsp;

7.  If $\int f\mbox{ }d\mu$ exists, then $|\int f\mbox{ }d\mu|\le \int |f|\mbox{ }d\mu$. 

    * $-|f|\le f \le |f|\implies -\int|f|d\mu=\int-|f|d\mu\le \int f\mbox{ }d\mu \le \int|f|d\mu\implies|\int f\mbox{ }d\mu|\le \int |f|\mbox{ }d\mu$.

&nbsp;&nbsp;


##### Theorem(Extended monotonicity)
Assume that $f\le g$ a.e. If $\int f\mbox{ }d\mu$ exists and $\int f\mbox{ }d\mu>-\infty$, then $\int g\mbox{ }d\mu$ exists. 

Similarly, if $\int g\mbox{ }d\mu$ exists and $\int g\mbox{ }d\mu<\infty$, then $\int f\mbox{ }d\mu$ exists. In either case, $\int f\mbox{ }d\mu\le \int g\mbox{ }d\mu$.   


&nbsp;&nbsp;

[back](../probability1.html)

