---
title: "2.9. Product Measure"
output: html_document
---

<style type="text/css">

body, td {
   font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

<br>
<br>


#### Definition
If $(\Omega_1, \mathcal{F}_1)$ and $(\Omega_2, \mathcal{F}_2)$ are measurable spaces, then any set of the form

$A_1\times A_2=\{(\omega_1,\omega_2): \omega_1\in A_1, \omega_2\in A_2\}$, with $A_1\in \mathcal{F}_1$ and $A_2\in \mathcal{F}_2$, is called a measurable rectangle.

The product $\sigma$-field, denoted $\mathcal{F}_1\times \mathcal{F}_2$ is defined to be the $\sigma$-field on $\Omega_1\times \Omega_2$ generated by the class of measurable rectangles. Thus if
$$
\text{Rect}(\mathcal{F_1},\mathcal{F_2})=\{A_1\in \mathcal{F}_1, A_2\in \mathcal{F}_2\}
$$
represents the class of measurable rectangles, then 
$$
\mathcal{F_1}\times \mathcal{F_2}:=\sigma(\text{Rect}(\mathcal{F_1},\mathcal{F_2})).
$$
More generally, if $(\Omega_1,\mathcal{F}_1),\ldots,(\Omega_k,\mathcal{F}_k)$ are measurable spaces, then 
$$
\times_{i=1}^k\mathcal{F}_i:=\sigma(\text{Rect}(\mathcal{F_1},\ldots\mathcal{F_k}))
$$
where 
$$
\text{Rect}(\mathcal{F_1},\ldots,\mathcal{F_k})=\{A_1\times\cdots A_k: A_i\in  \mathcal{F}_i,i=1,\ldots,k\}.
$$


<br>
<br>

##### Proposition
Suppose that $(\Omega_1,\mathcal{F}_1)$ and $(\Omega_2\mathcal{F}_2)$ are measurable spaces, and that $\mathcal{A}_1$ and $\mathcal{A}_2$ are generating classes for $\mathcal{F}_1$ and $\mathcal{F}_2$, respectively, with $\Omega_1\in \mathcal{A}_1$, $\Omega_2\in \mathcal{A}_2$. Then,
$$
\mathcal{F_1}\times \mathcal{F_2}:=\sigma(\text{Rect}(\mathcal{A_1},\mathcal{A_2})).
$$
More generally, if $(\Omega_1,\mathcal{F}_1),\ldots,(\Omega_k,\mathcal{F}_k)$ are measurable spaces, with $\mathcal{F}_i=\sigma(\mathcal{A}_i)$, and $\Omega_i\in \mathcal{A}_i$, $i=1,\ldots,n$, then 
$$
\times_{i=1}^k\mathcal{F}_i:=\sigma(\text{Rect}(\mathcal{A_1},\ldots\mathcal{A_k}))
$$

<br>
<br>

##### Corollary
If $(\Omega_1,\mathcal{F}_1),\ldots,(\Omega_{m+n},\mathcal{F}_{m+n})$ are measurable spaces, for some $m,n\ge 1$, then
$$
\times_{i=1}^{m+n}\mathcal{F}_i=\left(\times_{i=1}^{m}\mathcal{F}_i\right)\times \left(\times_{j=m+1}^{m+n}\mathcal{F}_i\right).
$$

<br>
<br>

##### Proposition
If $(\Omega,\mathcal{F}),(\Omega_1,\mathcal{F}_1)$ and $(\Omega_2,\mathcal{F}_2)$ are measurable spaces, and $T:\Omega\rightarrow \Omega_1\times \Omega_2$, with $T(\omega)=(T_1(\omega), T_2(\omega))$, then $T$ is measurable-$\mathcal{F}/(\mathcal{F}_1\times\mathcal{F}_2)$ if and only if each $T_i$ is measurable-$\mathcal{F}/(\mathcal{F}_i$, $i=1,2$.

More generally, if $(\Omega,\mathcal{F}),(\Omega_1,\mathcal{F}_1)\ldots(\Omega_k,\mathcal{F}_k)$ are measurable spaces, then $T$ is measurable-$\mathcal{F}/(\mathcal{F}_1\times\cdots\times\mathcal{F}_k)$ if and only if each $T_i$ is measurable-$\mathcal{F}/(\mathcal{F}_i$, $i=1,2,\ldots,k$.

<br>
<br>

##### Theorem(Existence and Uniqueness of Finite Product Measure)
If $(\Omega_1, \mathcal{F}_1, \mu_1)$ and $(\Omega_2, \mathcal{F}_2, \mu_2)$ are $\sigma$-finite measure spaces, then there exists a unique measure $\mu$ on $\mathcal{F}_1\times\mathcal{F}_2$ satisfying
$$
\mu(A_1\times A_2)=\mu_1(A_1)\mu_2(A_2)\mbox{ }\mbox{ }\mbox{ }\mbox{ for all } A_1\in \mathcal{F}_1, A_2\in \mathcal{F_2}.
$$
Moreover, $\mu$ is $\sigma$-finite on $\mathcal{F}_1\times\mathcal{F}_2$.

<br>

##### Definition
This measure $\mu$ in the theorem is called a **product measure**, and is usually denoted $\mu_1\times \mu_2$. The measurable space $(\Omega_1\times\Omega_2, \mathcal{F}_1\times \mathcal{F}_2, \mu_1\times\mu_2 )$ is called a *product measure space*.

   * 결론은 product measure는 각 measurable space에서의 measure들의 곱과 같다. 


<br>
<br>

##### Lemma
If $\mathcal{A}_1$ is a semiring on $\Omega_1$ and $\mathcal{A}_2$ is a semiring on $\Omega_2$, then the class $\text{Rect}(\mathcal{A}_1, \mathcal{A}_2)$ is a semiring on $\Omega_1\times\Omega_2$.


  * 증명

1. $\phi=\phi\times \phi\in \text{Rect}(\mathcal{A}_1\times \mathcal{A}_2).$

2. If $A_1\times A_2,B_1 \times B_2\in \text{Rect}(\mathcal{A}_1\times \mathcal{A}_2)$, then
$$
(A_1\times A_2)\cap (B_1\times B_2) =  (A_1\times B_1)\cap (A_2\times B_2)\in \text{Rect}(\mathcal{A}_1\times \mathcal{A}_2).
$$
3. $A_1\times A_2,B_1\times B_2 \in\text{Rect}(\mathcal{A}_1\times \mathcal{A}_2)$, with $A_1\times A_2\subset B_1\times B_2$ 라고 가정하자. 그렇다면 $A_1\subset B_1$이고 $A_2\subset B_2$이다. 따라서,
   $$
   B_1\times B_2-A_1\times A_2= [(B_1-A_1)\times B_2]\uplus [(B_2-A_2)\times A_1]=\left[\uplus_{i=1}^m (C_{1i}\times B_2)\right]\uplus \left[\uplus_{j=1}^n (C_{2j}\times A_1)\right].
   $$
(큰사각형에서 작은 사각형을 뺀다고 생각하면 된다.)

<br>
<br> 
   
##### 정리

전에 Uniqueness Theorem과 Caratheodory Extension Theorem을 배웠었다. Uniqueness Theorem은 두 measure가 주어진 field $\mathcal{P}$에서 agree한다면 $\sigma(\mathcal{P})$에서도 agree한다는 내용이다.  Caratheodory Extension Theorem은 주어진 field $\mathcal{P}$에서 정의된 measure $\mu$가 $\sigma(\mathcal{P})$에서도 unique하게 정의된다는 것을 의미한다. 

이 내용을 똑같이 Product measure에서도 증명할 수 있다 (너무 복잡하여 생략). 
   
<br>
<br>



[back](../probability1.html)

