---
title: "7.2. Definition and Elementary Properties"
output: html_document
---



<style type="text/css">
  body, td {
    font-size: 15px;
  }
pre {
  font-size: 15px
}
</style>

<br>
<br>

#### Definition
The **characteristic function** of a probability measure $\mu$ on $(\mathbb{R},\mathcal{R})$ is the function $\phi:\mathbb{R}\rightarrow \mathbb{C}$ defined by
$$
\phi(t)=\int e^{itx}\mbox{ }d\mu(x)=\int \cos(tx)\mbox{ }d\mu(x)+ i\int \sin(tx)\mbox{ }d\mu(x).
$$
If $F$ is the distribution function corresponding to $\mu$, or if $X$ is a random variable with distribution $\mu$, then we say that $F$ or $X$ has characteristic function $\phi$. Of course we then may write
$$
\phi(t)=\int e^{itx}dF(x)= \int \cos(tx)\mbox{ }dF(x)+ i\int \sin(tx)\mbox{ }dF(x),
$$
or
$$
\phi(t)=E\left[e^{itX}\right]=E\left[\cos(tX)\right]+iE\left[\sin(tX)\right].
$$

<br>
<br>

#### Proposition (Elementary Properties of the Characterisric Function)

Let $\phi$ be the characteristic function of a random variable $X$. Then,

1. $\phi(0)=1$;

2. $|\phi(t)|\le 1$ (Modulus Inequality);

3. $\phi$ is uniformly continuous;

4. $\text{Re}\{\phi(t)\}=E[\cos(tX)]$ is an even function of $t$, and $\text{Im}\{\phi(t)\}=E[\sin(tX)]$ is odd;

5. $\phi(-t)=\overline{\phi(t)}$;

   * $e^{-itX}=\cos(-tX)+i\sin(-tX)=\cos(tX)-i\sin(tX)=\overline{e^{itX}}.$

6. For $a,b\in\mathbb{R}$, $\phi_{aX+b}(t)=e^{ibt}\phi_X(at)$, in particular, $\phi_{-X}(t)=\phi_X(-t)=\overline{\phi_X(t)}$.

   * $e^{it(aX+b)}=e^{it(aX)}e^{ibt}=e^{i(at)X}e^{ibt}=e^{ibt}\phi_X(at)$.


7. $\phi_X$ is a real valued function $\iff$ $X$ is symmetrically distributed about the origin i.e., $-X\sim X$.

   *  6번에 의해 $\phi_X(t)\stackrel{\text{symm}}=\phi_{-X}(t)=\phi_X(-t)=\overline{\phi_X(t)}\implies \phi_X(t)=\overline{\phi_X(t)}.$

8. If $X$ and $Y$ are independent, then $\phi_{X+Y}(t)=\phi_X(t)\phi_Y(t).$

<br>
<br>

#### Lemma
For any $x\in \mathbb{R}$,
$$\begin{eqnarray*}
\left|e^{ix}-\sum_{k=0}^n\frac{(ix)^k}{k!}\right|&\le& \min\left\{\frac{|x|^{n+1}}{(n+1)!}, \frac{2|x|^{n}}{n!}  \right\}.
\end{eqnarray*}$$
Thus, we have at $n=0$, and $n=1$,
$$\begin{eqnarray*}
\left|e^{ix}-1\right| &\le& \min\left\{|x|, 2  \right\},\\
\left|e^{ix}-(1+ix) \right| &\le& \min\left\{\frac{|x|^2}{2}, 2|x|  \right\}.
\end{eqnarray*}$$

<br>
<br>

#### Lemma
If $E[|X|^n]<\infty$ for some integer $n\ge 1$, then $\phi(t)=E[e^{itX}]$ satisfies

$$
\left| \phi(t)-\sum_{k=0}^n\frac{(it)^k}{k!}E(X^k) \right| \le E\left[\min\left\{\frac{|tX|^{n+1}}{(n+1)!}, \frac{2|tX|^{n}}{n!}  \right\}\right].
$$

<br>

   * 증명 :

$$\begin{eqnarray*}
\left| \phi(t)-\sum_{k=0}^n\frac{(it)^k}{k!}E(X^k) \right| &=&\left| E(e^{itX})-\sum_{k=0}^n\frac{(it)^k}{k!}E(X^k) \right|  \\
&=& \left| E\left[e^{itX}-\sum_{k=0}^n\frac{(itX)^k}{k!}\right] \right| \\
&\le& E\left[\left| e^{itX}-\sum_{k=0}^n\frac{(itX)^k}{k!}\right|\right]  \\
&\le& E\left[\min\left\{\frac{|tX|^{n+1}}{(n+1)!}, \frac{2|tX|^n}{n!} \right\}\right].
\end{eqnarray*}$$
   
<br>
<br>

#### Theorem
If $E[|X|^n]<\infty$ for some integer $n\ge 1$, then
$$
\phi(t)=\sum_{k=0}^n\frac{(it)^k}{k!}E(X^k)+R_n(t),
$$
where $R_n(t)=o(|t|^n)$ as $t\rightarrow 0$.

<br>

   * 이전 lemma에 의해

   $$
   |R_n(t)|\le E\left[\min\left\{\frac{|tX|^{n+1}}{(n+1)!}, \frac{2|tX|^{n}}{n!}  \right\}\right]= |t|^nE\left[\min\left\{  \frac{|t||X|^{n+1}}{(n+1)!}, \frac{2|X|^{n}}{n!} \right\}\right].
   $$
  Now,
  $$
  0\le \min\left\{  \frac{|t||X|^{n+1}}{(n+1)!}, \frac{2|X|^{n}}{n!}\right\}\le \begin{cases}\frac{2|X|^{n}}{n!} &\mbox{integrable} \\  \frac{|t||X|^{n+1}}{(n+1)!}\rightarrow0 & \mbox{ as } t\rightarrow 0.\end{cases}
  $$
  Thus, by D.C.T
  $$
  \frac{R_n(t)}{|t|^n}=E\left[\min\left\{  \frac{|t||X|^{n+1}}{(n+1)!}, \frac{2|X|^{n}}{n!} \right\}\right]\rightarrow 0 \mbox{ }\mbox{ }\mbox{ as }t\rightarrow 0.
  $$
  
  * 즉, 특성함수 $\phi(t)$는 Taylor expansion한 n번째까지 항 기대값 합과 나머지로 split할 수 있고, 그 나머지 파트 $R_n(t)$는 $\frac{R_n(t)}{|t|^n}\rightarrow 0$ as $t\rightarrow 0$이다.  

     
<br>
<br>

[back](../probability1.html)   