---
title: "8.1. The central Limit Theorem"
output: html_document
---

<style type="text/css">
  body, td {
    font-size: 15px;
  }
pre {
  font-size: 15px
}
</style>

<br>
<br>

중요하다(i.i.d 조건)

#### Theorem (Classical CLT for i.i.d Summands)
If $X_n,n\ge 1$ are **i.i.d** random variables with $E(X_1)=c$ and $\text{Var}(X_1)=\sigma^2$, where $0<\sigma^2<\infty$, then
$$
\frac{S_n-nc}{\sigma\sqrt{n}}\leadsto Z\sim N(0,1).
$$

   * 우리가 가장 많이 봐왔던 CLT이다 $\left(\frac{\bar X_n-E(X_1)}{\sigma/\sqrt{n}}=\frac{S_n-nc}{\sigma\sqrt{n}}\leadsto Z\sim N(0,1)\right)$.
   
   * **i.i.d** 조건이 있다는 것에 주목해야 한다. 

<br>
<br>

매우 중요하다(independent 조건)

#### Theorem (Linderberg-Feller Central Limit Theorem)
Suppose that for $n\ge 1$, $X_{n,1},\ldots, X_{n,r_n}$ are **independent** random variables with
$$
E(X_{n,k})=0\mbox{ }\mbox{ }\mbox{ }\mbox{ and }\mbox{ }\mbox{ }\mbox{ } \sigma_{n,k}^2=E(X_{n,k}^2)<\infty,\mbox{ }\mbox{ }k=1,\ldots,r_n.
$$
Let 
$$
S_n=X_{n,1}+\cdots+X_{n,r_n}\mbox{ }\mbox{ }\mbox{ and }\mbox{ }\mbox{ }\mbox{ }s_n^2=\sigma_{n,1}^2+\cdots+\sigma_{n,r_n}^2,
$$
and assume that $s_n^2>0$ for $n$ large. Then

1. $\frac{S_n}{s_n}\leadsto Z\sim (0,1)$ as $n\rightarrow \infty$;

2. $\frac{\max_{1\le k\le r_n}\sigma^2_{n,k}}{s_n^2}\rightarrow 0$ as $n\rightarrow \infty$,

are necessary and sufficient that the **Linderberg condition** hold:
$$
\lim_{n\rightarrow \infty}\frac{1}{s_n^2}\sum_{k=1}^{r_n}\int_{\{|X_{n,k}|\ge \epsilon s_n \}}X_{n,k}^2\mbox{ }dP=0\mbox{ }\mbox{ }\mbox{ for all }\mbox{ }\mbox{ }\epsilon>0.
$$

<br>
    
  * 증명은 복잡하므로 생략한다.

  * 우리는 항상 Linderberg Feller CLT를 사용할때 변수를 $r_n=n$에 대한 $X_{n,k}=X_k$, $1\le k\le n$로 생각하여 적용할 것이다.

  * 주로 주어진 독립변수들에 대해 Linderberg 조건이 만족하는지 check하고 만족한다면 $\frac{S_n}{s_n}\leadsto Z\sim(0,1)$로 문제를 해결할 것이다.

<br>
<br>

#### Proposition
If $X_n,n\ge 1$ are independent random variables with
$$
E(X_n)=0\mbox{ }\mbox{ }\mbox{ }\mbox{ and }\mbox{ }\mbox{ }\mbox{ }\text{Var}(X_n)=\sigma_n^2, \mbox{ }\mbox{ }\mbox{ }n\ge 1,
$$
and $s_n^2=\sum_{k=1}^n\sigma_k^2$, then the Linderberg condition
$$
\lim_{n\rightarrow \infty}\frac{1}{s_n^2}\sum_{k=1}^{r_n}\int_{\{|X_{n,k}|\ge \epsilon s_n \}}X_{n,k}^2\mbox{ }dP=0\mbox{ }\mbox{ }\mbox{ for all }\mbox{ }\mbox{ }\epsilon>0,
$$
is equivalent to 
$$
\lim_{n\rightarrow \infty}\frac{1}{s_n^2}\sum_{k=1}^{r_n}\int_{\{|X_{n,k}|\ge \epsilon s_k \}}X_{n,k}\mbox{ }dP=0\mbox{ }\mbox{ }\mbox{ for all }\mbox{ }\mbox{ }\epsilon>0.
$$

   * 즉, Linderberg condition에서의 적분 구간에서  ${\{|X_{n,k}|\ge \epsilon s_n \}}$가 ${\{|X_{n,k}|\ge \epsilon s_k \}}$로 바뀌어도 결과는 같다.

<br>
<br>






<br>
<br>


#### Corollary (Lyapounov's Central Limit Theorem)
For each $n\ge 1$, let $X_{n,1},\ldots X_{n,{r_n}}$ be independent random variables with
$$
E[X_{n,k}]=0\mbox{ }\mbox{ }\mbox{ }\mbox{ and }\mbox{ }\mbox{ }\mbox{ }\text{Var}[X_{n,k}]=\sigma_{n,k}^2, \mbox{ }\mbox{ }\mbox{ }k=1,\ldots,r_n.,
$$
and let $s_n^2=\sum_{k=1}^{r_n}\sigma_{n,k}^2$. If there exists a constant $\delta>0$ such that **Lyapounov's condition**
$$
\lim_{n\rightarrow \infty}\frac{1}{s_n^{2+\delta}}\sum_{k=1}^{r_n}E\left[|X_{n,k}|^{2+\delta}\right]=0
$$
holds, then $S_n/s_n\leadsto Z\sim N(0,1)$.

<br>

  * 거의 대부분의 경우 $\delta=1$로 놓고 Lyapounov 조건이 만족하는지 확인한다.
    
<br>
<br>

#### Corollary

Suppose that $X_n,n\ge 1$ are independent, uniformly bounded random variables with mean 0. If
$$
s_n^2=\text{Var}(S_n)\rightarrow \infty \mbox{ }\mbox{ }\mbox{ as }\mbox{ }n\rightarrow \infty,
$$
then, $S_n/s_n\leadsto Z\sim N(0,1)$

<br>

  * 증명: Uniformly bounded된 변수를 $|X_n|\le B$라고 하자. With $\delta=1$,

  $$
  \frac{1}{s_n^3}\sum_{k=1}^nE\left[|X_k|^3\right]\le \frac{B}{s_n^3}\sum_{k=1}^nE\left[X_k^2\right]=\frac{B}{s_n}\rightarrow 0.
  $$
  때문에 Lyapounov condition이 만족한다. 
   

<br>
<br>

##### 예제

Let $1\le \alpha<\infty$ and let $X_n,n\ge1$ be **independent** random variables with 
$$
P(X_n=n^\alpha)=P(X_n=-n^\alpha)=\frac{1}{6}n^{-2(\alpha-1)},
$$
and
$$
P(X_n=0)=1-\frac{1}{3}n^{-2(\alpha-1)}.
$$
Then, 
$$
\frac{S_n}{s_n}\leadsto Z\sim N(0,1)\mbox{ }\mbox{ }\iff \mbox{ }\mbox{ } 1\le \alpha <\frac{3}{2}.
$$

<br>

  * Linderberg Feller 조건과 Lyapounov 조건이 성립하는지 각각 확인해 볼 수 있다.
  
<br>
<br>


[back](../probability1.html)   