---
title: "3.2. Overdispersion"
output: html_document
---

<style type="text/css">
  
  body, td {
    font-size: 15px;
  }
pre {
  font-size: 15px
}
</style>

매우 중요

##### Remark(overdispersion)
Suppose $Y\sim \text{poisson}(\lambda)$. Then, it is possible that this model includes only some of explanatory variables, i.e., there exists some latent variables we cannot figure out. Because of this, for $Y\sim \text{poisson}(\lambda)$, $\lambda$ can vary as well.

Let $E(\lambda)=\mu$, $\text{Var}(\lambda)=\sigma^2$. Then, by the Tower property,
$$\begin{eqnarray*}
E(Y)&=&E_\lambda\{E(Y|\lambda) \}= E\{\lambda \}=\lambda,\\
\text{Var}(Y)&=&E_\lambda\{ \text{Var}(Y|\lambda) \}+\text{Var}_\lambda\{ E(Y|\lambda) \}\\
&=&E(\lambda)+\text{Var}(\lambda)=\mu+\sigma^2>\mu.
\end{eqnarray*}$$
Thus, we can say, there is **overdispersion** relative to the poisson model. 

&nbsp;&nbsp;

##### Remark(Models allowing overdispersion)
We have three approaches dealing with the overdispersion:

1. two-parameter family that permits $\text{Var}(Y)>E(Y)$, for example, **negative binomial**.

2. **quasi-likelihood** approach assuming $\text{Var}(Y)=cE(Y)$, without assuming a particular parametric distribution function for $Y$.

3. **mixture modeling** approach. For example, let $Y|\lambda\sim \text{poisson}(\lambda)$, $\lambda\sim \Gamma(\alpha, \beta)$. 

&nbsp;&nbsp;


지금부터 이 3가지 approach에 대해 자세히 derivation을 할 것이다. 

##### Remark(Negative binomial regression)
Suppose that given $\lambda$, $Y\sim \text{poisson}(\lambda)$ and $\lambda\sim\Gamma(k,k/\mu).$ Then,
$$
f(\lambda;k,\mu)= \frac{(k/\mu)^k}{\Gamma(k)}\exp\left(-\frac{k\lambda }{\mu}\right), \mbox{ }\lambda>0.
$$

We have $E(\lambda)=\mu$ and $\text{Var}(\lambda)=\mu^2/k$.

Then, Greenwood and Yule (1920) showed that $Y$ has probability mass function
$$
P(Y=y; k, \mu)= \frac{\Gamma(y+k)}{\Gamma(k)\Gamma(y+1)}\left(\frac{\mu}{\mu+k}\right)^y \left(1-\frac{\mu}{\mu+k}\right)^k,
$$
for $y=0,1,2,\ldots.$. This is p.m.f of negative binomial distribution.

Note that

$$
E(Y)= \mu, \mbox{ } \text{Var}(Y)=\mu+\mu^2/k.
$$
As $n\rightarrow \infty$, $\text{Var}(\lambda)\rightarrow 0$ and $\text{Var}(Y)\rightarrow \mu$ (Negative bionmial $\rightarrow$ poisson).  

   * $Y$의 marginal 분포는 $Y|\lambda$의 분포와 $\lambda$의 분포를 곱하여 joint density를 구한 다음, $\lambda$에 대하여 적분하면 구할 수 있다. 
   
   * 일반적인 Negative binomial 분포의 mean은 $E(X)=\frac{rp}{1-p}$, Variance는 $\text{Var}(X)=\frac{rp}{(1-p)^2}$이다.(notation 설명 생략: $r$은 우리 예제에선 $k$). 
     $$
    \because E(Y)=\frac{k \frac{\mu}{\mu+k} }{\frac{k}{\mu+k}}=\mu, \mbox{ }  \text{Var}(Y)=\frac{k \frac{\mu}{\mu+k} }{\frac{k^2}{(\mu+k)^2}}=\frac{\mu}{k}(\mu+k)=\mu+\mu^2/k.
     $$
     
&nbsp;&nbsp;

Note that we take $g(\mu_i)=\sum_j\beta_jx_{ij}$ and fixed $k$ (unknown) for all $i$. Usually, $g(\mu_i)=\log \mu_i$.
     
